"""initial schema

Revision ID: 8810866cbee0
Revises:
Create Date: 2026-07-24 13:44:33.377925
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8810866cbee0"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS inventory")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inventory",
        sa.Column("sku", sa.String(length=64), nullable=False),
        sa.Column("on_hand", sa.Integer(), nullable=False),
        sa.Column("reserved", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint("on_hand >= 0", name="ck_inventory_on_hand_non_negative"),
        sa.CheckConstraint("reserved >= 0", name="ck_inventory_reserved_non_negative"),
        sa.CheckConstraint("reserved <= on_hand", name="ck_inventory_reserved_lte_on_hand"),
        sa.PrimaryKeyConstraint("sku"),
        schema="inventory",
    )
    op.create_table(
        "outbox",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=255), nullable=False),
        sa.Column("payload", sa.String(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="inventory",
    )
    op.create_index(
        "ix_inventory_outbox_unpublished",
        "outbox",
        ["published_at"],
        unique=False,
        schema="inventory",
        postgresql_where=sa.text("published_at IS NULL"),
    )
    op.create_table(
        "reservations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("sku", sa.String(length=64), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["sku"], ["inventory.inventory.sku"], ondelete="CASCADE"),
        sa.CheckConstraint("qty > 0", name="ck_reservations_qty_positive"),
        sa.PrimaryKeyConstraint("id"),
        schema="inventory",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reservations", schema="inventory")
    op.drop_index(
        "ix_inventory_outbox_unpublished",
        table_name="outbox",
        schema="inventory",
        postgresql_where=sa.text("published_at IS NULL"),
    )
    op.drop_table("outbox", schema="inventory")
    op.drop_table("inventory", schema="inventory")
    # ### end Alembic commands ###
