"""initial schema

Revision ID: 3a6f18ca326a
Revises:
Create Date: 2026-07-24 13:44:34.349189
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3a6f18ca326a"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS orders")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "PAID", "FULFILLED", "CANCELLED", "FAILED", name="order_status", schema="orders"),
            nullable=False,
        ),
        sa.Column("total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "idempotency_key", name="uq_orders_user_idempotency_key"),
        schema="orders",
    )
    op.create_index("ix_orders_user_id_status", "orders", ["user_id", "status"], unique=False, schema="orders")
    op.create_table(
        "outbox",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=255), nullable=False),
        sa.Column("payload", sa.String(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="orders",
    )
    op.create_index(
        "ix_orders_outbox_unpublished",
        "outbox",
        ["published_at"],
        unique=False,
        schema="orders",
        postgresql_where=sa.text("published_at IS NULL"),
    )
    op.create_table(
        "order_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("product_name", sa.String(length=255), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["order_id"], ["orders.orders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="orders",
    )
    op.create_table(
        "saga_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("step", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["order_id"], ["orders.orders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="orders",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("saga_log", schema="orders")
    op.drop_table("order_items", schema="orders")
    op.drop_index(
        "ix_orders_outbox_unpublished",
        table_name="outbox",
        schema="orders",
        postgresql_where=sa.text("published_at IS NULL"),
    )
    op.drop_table("outbox", schema="orders")
    op.drop_index("ix_orders_user_id_status", table_name="orders", schema="orders")
    op.drop_table("orders", schema="orders")
    # ### end Alembic commands ###
