"""initial schema

Revision ID: ed22f9c3db1f
Revises:
Create Date: 2026-07-24 13:44:31.264501
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ed22f9c3db1f"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS identity")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outbox",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=255), nullable=False),
        sa.Column("payload", sa.String(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="identity",
    )
    op.create_index(
        "ix_identity_outbox_unpublished",
        "outbox",
        ["published_at"],
        unique=False,
        schema="identity",
        postgresql_where=sa.text("published_at IS NULL"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("oidc_sub", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("oidc_sub"),
        schema="identity",
    )
    op.create_index(op.f("ix_identity_users_email"), "users", ["email"], unique=True, schema="identity")
    op.create_index(op.f("ix_identity_users_oidc_sub"), "users", ["oidc_sub"], unique=False, schema="identity")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_identity_users_oidc_sub"), table_name="users", schema="identity")
    op.drop_index(op.f("ix_identity_users_email"), table_name="users", schema="identity")
    op.drop_table("users", schema="identity")
    op.drop_index(
        "ix_identity_outbox_unpublished",
        table_name="outbox",
        schema="identity",
        postgresql_where=sa.text("published_at IS NULL"),
    )
    op.drop_table("outbox", schema="identity")
    # ### end Alembic commands ###
