"""initial schema

Revision ID: 27123711f655
Revises:
Create Date: 2026-07-24 13:44:32.436557
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "27123711f655"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS catalog")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outbox",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=255), nullable=False),
        sa.Column("payload", sa.String(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="catalog",
    )
    op.create_index(
        "ix_catalog_outbox_unpublished",
        "outbox",
        ["published_at"],
        unique=False,
        schema="catalog",
        postgresql_where=sa.text("published_at IS NULL"),
    )
    op.create_table(
        "products",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("merchant_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("category", sa.String(length=255), nullable=True),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("image_key", sa.String(length=1024), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version_id", sa.Integer(), nullable=False),
        sa.CheckConstraint("price > 0", name="ck_products_price_positive"),
        sa.PrimaryKeyConstraint("id"),
        schema="catalog",
    )
    op.create_index("ix_products_category", "products", ["category"], unique=False, schema="catalog")
    op.create_index("ix_products_merchant_id", "products", ["merchant_id"], unique=False, schema="catalog")
    op.create_index("ix_products_name", "products", ["name"], unique=False, schema="catalog")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_products_name", table_name="products", schema="catalog")
    op.drop_index("ix_products_merchant_id", table_name="products", schema="catalog")
    op.drop_index("ix_products_category", table_name="products", schema="catalog")
    op.drop_table("products", schema="catalog")
    op.drop_index(
        "ix_catalog_outbox_unpublished",
        table_name="outbox",
        schema="catalog",
        postgresql_where=sa.text("published_at IS NULL"),
    )
    op.drop_table("outbox", schema="catalog")
    # ### end Alembic commands ###
